#!/usr/bin/env bash

dirs=(lib doc man bin sbin share etc)
for dir in ${dirs[@]}; do
    mkdir -p $__dependencyEnv_sandbox/_build/ocamlfind/$dir
done

if [ ! -z "$OCAMLLIB" ]
then
    ln -sf $OCAMLLIB $__dependencyEnv_sandbox/_build/ocamlfind/lib/ocaml
fi

read -d '' findlibconf <<EOF
destdir="$__dependencyEnv_sandbox/_build/ocamlfind/lib"
path="$FINDLIB"
ocamlc="ocamlc.opt"
ocamlopt="ocamlopt.opt"
ocamldep="ocamldep.opt"
ocamldoc="ocamldoc.opt"
EOF
echo -e $findlibconf > $__dependencyEnv_sandbox/_build/ocamlfind/lib/findlib.conf
